config/routes.rb
RailsBbPortfolio::Application.routes.draw do
  
  resources :project_images
  
  scope 'api' do
    resources :projects
    resources :people
  end

  root :to => 'projects#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birthdate, :gender, :name, :text

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :date
  
  has_many :project_images
  
end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base
  attr_accessible :name, :img, :project_id
  
  has_attached_file :img,
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename",
    :styles => { :medium => "900x900>", :full => "1920x1920>", :thumb => "200x200>" }
  
  belongs_to :project
  
  def full_image
    img.url(:full)
  end
  
  def medium_image
    img.url(:medium)
  end
  
  def thumb_image
    img.url(:thumb)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/project_images_controller.rb
class ProjectImagesController < ApplicationController
  # GET /project_images
  # GET /project_images.json
  def index
    @project_images = ProjectImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_images }
    end
  end

  # GET /project_images/1
  # GET /project_images/1.json
  def show
    @project_image = ProjectImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_image }
    end
  end

  # GET /project_images/new
  # GET /project_images/new.json
  def new
    @project_image = ProjectImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_image }
    end
  end

  # GET /project_images/1/edit
  def edit
    @project_image = ProjectImage.find(params[:id])
  end

  # POST /project_images
  # POST /project_images.json
  def create
    @project_image = ProjectImage.new(params[:project_image])

    respond_to do |format|
      if @project_image.save
        format.html { redirect_to @project_image, notice: 'Project image was successfully created.' }
        format.json { render json: @project_image, status: :created, location: @project_image }
      else
        format.html { render action: "new" }
        format.json { render json: @project_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_images/1
  # PUT /project_images/1.json
  def update
    @project_image = ProjectImage.find(params[:id])

    respond_to do |format|
      if @project_image.update_attributes(params[:project_image])
        format.html { redirect_to @project_image, notice: 'Project image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_images/1
  # DELETE /project_images/1.json
  def destroy
    @project_image = ProjectImage.find(params[:id])
    @project_image.destroy

    respond_to do |format|
      format.html { redirect_to project_images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json do 
        render :json => @projects.to_json(
                  :include => { :project_images => { 
                    :only => [ :medium_image, :full_image, :thumb_image ],
                    :methods => [ :medium_image, :full_image, :thumb_image ] } })
      end                                      
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/project_images_helper.rb
module ProjectImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBbPortfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
	<%= yield %>
</div>

</body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :gender %>
    <%= f.input :birthdate %>
    <%= f.input :text %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Birthdate</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.gender %></td>
    <td><%= person.birthdate %></td>
    <td><%= person.text %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Gender:</b>
  <%= @person.gender %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @person.birthdate %>
</p>

<p>
  <b>Text:</b>
  <%= @person.text %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/project_images/_form.html.erb
<%= simple_form_for @project_image, :html => { :multipart => true } do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="inputs">
    <%= f.input :img %>
  </div>

  <div class="actions">
    <%= f.association :project %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/project_images/edit.html.erb
<h1>Editing project_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_image %> |
<%= link_to 'Back', project_images_path %>

app/views/project_images/index.html.erb
<h1>Listing project_images</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_images.each do |project_image| %>
  <tr>
    <td><%= project_image.name %></td>
    <td><%= link_to 'Show', project_image %></td>
    <td><%= link_to 'Edit', edit_project_image_path(project_image) %></td>
    <td><%= link_to 'Destroy', project_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project image', new_project_image_path %>

app/views/project_images/new.html.erb
<h1>New project_image</h1>

<%= render 'form' %>

<%= link_to 'Back', project_images_path %>

app/views/project_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project_image.name %>
</p>


<%= link_to 'Edit', edit_project_image_path(@project_image) %> |
<%= link_to 'Back', project_images_path %>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>